"""
event_engine.py — Centralized Idempotent Inventory Event Processor
Ensures strict idempotency: every event has a unique event_id and can never decrement/increment
inventory twice. Separates database inventory from instantaneous visual detections.
"""
import uuid
import json
from datetime import datetime
from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session
from ... import models
from ...websocket import manager
import asyncio

_main_loop: Optional[asyncio.AbstractEventLoop] = None

def set_main_loop(loop: asyncio.AbstractEventLoop):
    global _main_loop
    _main_loop = loop

def _safe_broadcast(payload: Dict[str, Any]):
    """Dispatches real-time WebSocket payloads safely from async or sync contexts."""
    try:
        global _main_loop
        if _main_loop and _main_loop.is_running():
            asyncio.run_coroutine_threadsafe(manager.broadcast(payload), _main_loop)
        else:
            try:
                loop = asyncio.get_running_loop()
                if loop and loop.is_running():
                    asyncio.ensure_future(manager.broadcast(payload))
            except RuntimeError:
                pass
    except Exception:
        pass

class EventEngine:
    """
    Centralized Event Processing Engine with strict idempotency and deduplication.
    """
    def __init__(self):
        # Set of processed event IDs to prevent duplicate execution
        self.processed_event_ids = set()

    def process_event(self, raw_event: Dict[str, Any], db: Session) -> Dict[str, Any]:
        """
        Takes an event generated by the state machine and executes stock modification once.
        """
        event_id = raw_event.get("event_id") or str(uuid.uuid4())
        
        # Idempotency check: Do not execute the same event twice!
        if event_id in self.processed_event_ids:
            print(f"[EventEngine] Duplicate event {event_id} skipped (Idempotency).")
            return raw_event

        event_type = raw_event.get("event_type", "PRODUCT_DETECTED")
        product_name = raw_event.get("product_name", "Unknown")
        tracking_id = raw_event.get("tracking_id")
        camera_id = raw_event.get("camera_id", 1)
        shelf_id = raw_event.get("shelf_id")
        quantity = raw_event.get("quantity", 1)
        confidence = float(raw_event.get("confidence", 0.95))
        status = raw_event.get("status", "VERIFIED")
        metadata = raw_event.get("metadata", {})

        # Find corresponding product in DB
        product = db.query(models.Product).filter(
            models.Product.name == product_name
        ).first()

        product_id = product.id if product else None
        initial_stock = product.stock if product else None
        current_stock = initial_stock

        # ── Stock Adjustments & Validations ───────────────────────
        alert_payload = None

        if event_type in ("PRODUCT_REMOVED", "SUSPICIOUS_REMOVAL") and product:
            product.stock = max(0, product.stock - quantity)
            product.updated_at = datetime.utcnow()
            current_stock = product.stock

            # Check for low stock or out of stock
            if product.stock <= product.threshold:
                severity = "CRITICAL" if product.stock == 0 else "WARNING"
                msg = (f"🚨 OUT OF STOCK: '{product_name}' has 0 units remaining!" 
                       if product.stock == 0 else 
                       f"⚠️ LOW STOCK: '{product_name}' has {product.stock} units left (Threshold: {product.threshold})")
                
                alert = models.Alert(
                    severity=severity,
                    alert_type="OUT_OF_STOCK" if product.stock == 0 else "LOW_STOCK",
                    product_name=product_name,
                    shelf_id=shelf_id,
                    tracking_id=tracking_id,
                    message=msg,
                    is_resolved=False,
                    timestamp=datetime.utcnow()
                )
                db.add(alert)
                alert_payload = {
                    "type": "alert",
                    "severity": severity,
                    "alert_type": alert.alert_type,
                    "product": product_name,
                    "message": msg,
                    "stock": current_stock,
                    "timestamp": datetime.utcnow().isoformat()
                }

        elif event_type in ("PRODUCT_PLACED", "RESTOCKING_DETECTED") and product:
            product.stock += quantity
            product.updated_at = datetime.utcnow()
            current_stock = product.stock

            # Automatically resolve low-stock alerts if stock recovered
            if product.stock > product.threshold:
                unresolved = db.query(models.Alert).filter(
                    models.Alert.product_name == product_name,
                    models.Alert.is_resolved == False
                ).all()
                for al in unresolved:
                    al.is_resolved = True
                    al.resolved_at = datetime.utcnow()

        elif event_type == "PRODUCT_MISPLACED":
            # Misplaced item alert
            msg = f"🔀 MISPLACED: '{product_name}' detected on incompatible shelf zone!"
            alert = models.Alert(
                severity="WARNING",
                alert_type="MISPLACED_PRODUCT",
                product_name=product_name,
                shelf_id=shelf_id,
                tracking_id=tracking_id,
                message=msg,
                is_resolved=False,
                timestamp=datetime.utcnow()
            )
            db.add(alert)
            alert_payload = {
                "type": "alert",
                "severity": "WARNING",
                "alert_type": "MISPLACED_PRODUCT",
                "product": product_name,
                "message": msg,
                "timestamp": datetime.utcnow().isoformat()
            }

        # ── Persist Event Audit Record ───────────────────────────
        ev_model = models.Event(
            event_id=event_id,
            event_type=event_type,
            product_name=product_name,
            product_id=product_id,
            tracking_id=tracking_id,
            camera_id=camera_id,
            shelf_id=shelf_id,
            quantity_removed=quantity if "REMOVED" in event_type else -quantity,
            confidence=confidence,
            status=status,
            metadata_json=json.dumps(metadata) if metadata else None,
            timestamp=datetime.utcnow()
        )
        db.add(ev_model)
        db.commit()

        # ── Trigger email notification state evaluation ───────────
        if product:
            try:
                from ...notifications.email_service import email_service
                email_service.evaluate_and_notify(product, db_session=db)
            except Exception as e:
                logger.warning(f"Error evaluating email notifications in event_engine: {e}")

        # Mark as processed for idempotency
        self.processed_event_ids.add(event_id)

        # ── Broadcast Real-Time Updates via WebSockets ───────────
        ws_event_payload = {
            "type": "event",
            "event_id": event_id,
            "event_type": event_type,
            "product": product_name,
            "tracking_id": tracking_id,
            "shelf_id": shelf_id,
            "quantity": quantity,
            "confidence": confidence,
            "status": status,
            "database_inventory": current_stock,
            "stock": current_stock,
            "metadata": metadata,
            "timestamp": datetime.utcnow().isoformat()
        }
        _safe_broadcast(ws_event_payload)

        if alert_payload:
            _safe_broadcast(alert_payload)

        return ws_event_payload

event_engine = EventEngine()
